### ISSUE TITLE
add log in cmd

### ISSUE THREAD

**Issue by sudimantidio** [zhycorp/whatsapp-bot#35]
there is a log like
"console.log (` Sticker Processed for $ {Runtime (t, moment ())} Seconds`) "

**Comment by mzrtamp** [comment]
Hi @sudimantidio 👋, what do you mean?

**Comment by mzrtamp** [comment]
> Hi @sudimantidio 👋, what do you mean?

Nvm, I see

**Comment by mzrtamp** [comment]
Hi there @sudimantidio, I have committed to a thing that you want. Anyway, this is untested, it's a good thing if you would like to help me with this!

**Comment by mzrtamp** [comment]
And sorry if I can't make it exactly the way you want it, but open pull requests if you want to contribute too!
