### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by limter1** [zhycorp/whatsapp-bot#50]
thanks YOU brother
I've been hoping for this feature for a long time
I ran an experiment but it turns a video or GIF into an unmoving poster

Please also add a caption below a sticker, such as package author and package name

**Comment by mzrtamp** [comment]
Can you provide proof? What it looks like?

**Comment by limter1** [comment]
<img src="https://f.top4top.io/p_186590e1j0.gif" border="0" />

**Comment by limter1** [comment]
https://up4net.com/uploads3/up4net-GIF-210208-205643.gif
[https://up4net.com/uploads3/up4net-GIF-210208-205643.gif](url)

**Comment by mzrtamp** [comment]
Hmm, we'll try to figure it out later

**Comment by limter1** [comment]
Thank you for your efforts
