### ISSUE TITLE
ReferenceError: getQrPng is not defined

### ISSUE THREAD

**Issue by Macrocalln** [zhycorp/whatsapp-bot#56]
<img width="797" alt="Captura de Pantalla 2021-02-24 a la(s) 11 20 42 p m" src="https://user-images.githubusercontent.com/79622808/109107302-1702ef00-76f7-11eb-87ae-4d479fe75e58.png">
<img width="797" alt="Captura de Pantalla 2021-02-24 a la(s) 11 20 58 p m" src="https://user-images.githubusercontent.com/79622808/109107314-1a967600-76f7-11eb-910d-704fec06a667.png">

**Comment by Macrocalln** [comment]
Yesterday it worked perfectly

**Comment by mzrtamp** [comment]
Hi, there is still a problem with the CI, I will try to fix this tomorrow as soon as possible 😉

**Comment by mzrtamp** [comment]
Thanks for reporting!
